pipeline {
    agent any
    tools {
        maven 'Maven 3' 
    }

 

    stages {
        stage('Example') {
            steps {

                withMaven(maven: 'Maven 3') {

                    bat 'mvn clean test'
                }
            }
        }
    }
}
